services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - type: bind
        source: ./frontend/vite.config.js
        target: /app/vite.config.js
      - type: volume
        target: /app/node_modules
    ports:
      - 5173:5173
  backend-dev:
    image: backend-dev
    build:
      context: backend
      dockerfile: Dockerfile
      target: dev  
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_ENV=development
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    depends_on:
      - db
  backend-prod:
    image: backend-prod
    build:
      context: backend
      dockerfile: Dockerfile
      target: prod  
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_ENV=production
    depends_on:
      - db
  db:
    image: postgres:17.4-bookworm
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
volumes:
  db_data:    


