# Generated by Django 5.1.5 on 2025-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog_Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("topic", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("author", models.CharField(max_length=100)),
            ],
        ),
    ]
